name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "atlassian-agent.jar"
      - "mysql-connector-java.jar"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: jira
            base_image: atlassian/jira-software
            tag: 9-jdk17
          - name: confluence
            base_image: atlassian/confluence
            tag: 9.2-jdk21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.name }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.name }}:${{ matrix.tag }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}:${{ matrix.tag }}
          no-cache: true
